language: python
python: 2.7
env:
  - TARGET=test
  - TARGET=coverage.sh
before_install:
  - sudo apt-get install ack-grep
  - sudo apt-add-repository ppa:chris-lea/node.js -y
  - sudo apt-get update 1>/dev/null
  - sudo apt-get install nodejs npm -y
  - npm install csslint -g
  - npm install jshint -g
install: 
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg

script: bin/$TARGET